site_name: Trixie Wiki
nav:
  - Home: index.md
  - Trixie Status: Trixie-Status.md
  - Account Codes: Account-Codes.md
  - Presentations:
      - Be a Good Cluster Citizen: BeAGoodClusterCitizen.html
  - General Info:
      - Available Software: Available-Software.md
      - Disk Quotas: quota.md
      - Hardware: Hardware.md
      - External Access:
          - Basic: External-Access-Setup.md
          - Advanced: External-Access-Advanced-Configuration.md
          - External HPC: External-HPC-Systems.md
      - Internal Access:
          - Basic: Internal-Access-Setup.md
          - Advanced: Internal-Access-Advanced-Configuration.md
      - Transfer Files: File-Transfers.md
      - TMP FS Backup: Temporary-Filesystem-Backups.md
      - Network and Connection: Networking-and-connectivity.md
  - FAQ & Example Workflows:
      - Quickstart: Running-jobs.md
      - Requeue Job: Automatically-Resuming-Requeueing.md
      - python venv: jobs-python-virtualenv.md
      - abinit: jobs-abinit.md
      - jupyterlab: jobs-jupyterlab.md
      - conda-RAPIDS: jobs-conda-RAPIDS.md
      - Pytorch Distributed on Multiple Nodes: SLURM,-pytorch-distributed-and-Multiple-Nodes.md
      - conda-pytorch: Jobs-conda-pytorch.md
  - Contribute: Contribute.md

theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: "Roboto"
    code: "Roboto Mono"

markdown_extensions:
  - toc:
      permalink: True
      toc_depth: 3
  - attr_list
  # Add icons/emojis [search](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search)
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search

extra_css:
  - stylesheets/extra.css
